FROM rust:1.57-buster as builder

RUN apt update -y  && \
    apt install cmake libclang1 clang -y 

ADD . /opt/src

WORKDIR /opt/src

RUN cargo build --release

FROM gcr.io/distroless/cc
COPY --from=builder /opt/src/target/release/bid-tracker-rs /usr/local/bin/app
CMD ["app"]
